language: ruby
rvm:
  - 1.9.2
  - 1.9.3-p327
  - 1.9.3-p545
  - 2.0.0
  - 2.1.1
  - 1.8.7
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-19mode
jdk:
  - oraclejdk7
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: 2.0.0
    - rvm: 2.1.1
